### ISSUE TITLE
Add skip-empty-xacts parameter?

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/osm-logical#1]
** There some changes by @joto in https://github.com/joto/osm-logical/commits/master which may have some impact on this issue **

Changing a single node in a changeset creates a fair amount of entries, most of which just indicate the beginning and the end of a transaction that didn't create any changes.

Also, any activity on the Rails port (or CGImap) involving a database transactions creates a BEGIN/END marker. This includes creating notes, writing messages, uploading gpx.

With about 1000 txns/s on karm, we would probably end up reading 120k B+C entries every minute.

```
5E/43B54600 1692931 B
5E/43B547F0 1692931 C
5E/43B546E0 1692932 B
5E/43B54820 1692932 C
5E/43B54820 1692933 B
5E/43B54930 1692933 C
5E/43B54930 1692934 B
5E/43B54A40 1692934 C
5E/43B54A40 1692935 B
5E/43B54B50 1692935 C
5E/43B54B50 1692936 B
5E/43B552C8 1692936 C
5E/43B552C8 1692937 B
5E/43B55438 1692937 C
5E/43B55438 1692938 B
5E/43B55548 1692938 C
5E/43B55548 1692939 B
5E/43B57B80 1692939 N n5004126921 v2 c1874432
5E/43B5AC08 1692939 C
5E/43B5AC08 1692940 B
5E/43B5AD18 1692940 C
5E/43B5AD18 1692941 B
5E/43B5AF78 1692941 C
5E/43B5B058 1692942 B
5E/43B5B168 1692942 C
5E/43B64030 1692943 B
5E/43B6D640 1692943 C
```

test_decoding comes with an optional parameter `skip-empty-xacts` to suppress those empty transactions. Maybe it would be good to have something similar for osm-logical as well?

Of course, osmdbt needs to set this parameter once it is supported.

**Comment by joto** [comment]
I believe we don't actually need those B/C log entries for anything. So maybe we should just not write them out?

**Comment by mmd-osm** [comment]
I think osmdbt still extracts the LSN from the "COMMIT" line, i.e. omitting all COMMIT lines would require some changes in osmdbt.

I'm wondering if leaving out some of the LSNs from the log could introduce some side effects, or if osmdbt just treats those LSNs as opaque strings that make up the osm-repl-*-lsn-*.log filename.

Original idea to only keep transactions with relevant changes (including B+C) would be https://github.com/mmd-osm/osm-logical/commit/64baf7a87e7f6a3a203a385bb5ddfc535ce4a381 (similar to the way this is being implemented in test_decoding.c)

**Comment by mmd-osm** [comment]
Fix in https://github.com/openstreetmap/osmdbt/commit/9ffcddcd9226dd705f42e312c88c010a0921193e#diff-bae3a48d58da5cabf24c7776fcd97aa2
